"""sec

Revision ID: 6e5997dd78e2
Revises: 5b473edc1b38
Create Date: 2023-08-18 20:04:31.333377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5997dd78e2'
down_revision = '5b473edc1b38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
