"""five

Revision ID: bd01ddcdecc9
Revises: 6e5997dd78e2
Create Date: 2023-08-18 21:29:54.018379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd01ddcdecc9'
down_revision = '6e5997dd78e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
